### ISSUE TITLE
carts not loading

### ISSUE THREAD

**Issue by EanimeiCCC** [jtothebell/fake-08#122]
I'm trying to load the birdswithguns cart and it's not even showing up on the list. I made sure to put it in the right folder. I think it might be a glitch?

**Comment by jtothebell** [comment]
Birds with guns won't currently work with FAKE-08 because of an incompatibility with nesting a multi-line string in a multi-line comment, but it should show up in the list and then return an error when you try to start it. Unfortunately, without more information about your specific issue, there isn't much I can do to trouble shoot it.
