### ISSUE TITLE
Suggestion: LibRetro Core API development

### ISSUE THREAD

**Issue by clems71** [jtothebell/fake-08#139]
Creating a FAKE-08 LibRetro Core would allow people to play cartridges (= ROMs) in any frontend they like (like OpenEMU).

The benefits I can think of are:
- Comply to a standard, meaning a unified experience from the user perspective. Same feature set as other emulators.
- Save state can be supported and integrated in frontend.

The good news is that there is no need to deal with frontend logic : display, audio, etc... We just deal with buffers and the frontend makes use of those - all wrapped in a single shared library. So I assume it's more about refactoring current code and creating a new target than starting from scratch.

Some useful links:
- [LibRetro Core Development](https://docs.libretro.com/development/cores/developing-cores/)
- [Dummy API compliant C sample](https://github.com/libretro/skeletor/blob/master/libretro.c)

**Comment by clems71** [comment]
Seems like FAKE-08 has better support and traction. But maybe I'm wrong.

**Comment by RandomMan25XX** [comment]
> Seems like FAKE-08 has better support and traction. But maybe I'm wrong.

While it definitely does, I'm just not sure why it's a good idea to have it added to Retroarch, I've never really seen many emulators continue separate builds after being integrated into Retroarch

**Comment by jtothebell** [comment]
Compiling as a librertro core has been in the back of my mind for a while, but I haven't made it a priority yet. I think I will eventually, because it seems like the best way to support some platforms like Android, but I'm not sure when that will be. Also, it will still take an additional piece for work for save states to work. And as far as providing builds goes, I will continue to only provide builds for platforms that PICO-8 does not have official support for, so no Windows, Mac, x86 linux, or raspberry pi compatible core builds.

**Comment by jtothebell** [comment]
There is a now a libretro core with support for a few platforms. There are still some issues with it, but I'm closing this general issue in favor of more specific ones.
