### ISSUE TITLE
Suggestion: Android Support

### ISSUE THREAD

**Issue by chrisasma103** [jtothebell/fake-08#149]
Currently, AFAIK, the only two ways to play Pico-8 games on Android is the P8 Player app, which doesn't support controllers and has input delay, and Retro8 on Retroarch, which is so unfinished even Celeste runs with graphical and sound glitches. I know that it would be possible to run Fake-08 via Citra to play Pico-8 games, but it would probably be better to run the app directly on Android rather than running an emulator within an emulator. Hopefully, this is possible.

**Comment by jtothebell** [comment]
Ha, I didn't ever think about using citra to play it on Android. While that sounds mildly interesting to try, I agree it is not ideal, and at some point would like to make an android version. I made a basic proof of concept, but binding controls and several other issues make me think Android is a good candidate for a libretro core, so that is probably the direction I'll go for Android support.

**Comment by bhall408** [comment]
FWIW, we're currently experimenting with bringing up fake08 in Argon (Android/Amazon)... Early days...

**Comment by jtothebell** [comment]
Android is now supported via a libretro core. Closing this issue.
