### ISSUE TITLE
MiyooMini-libretro crash when auto save state restore is enabled.

### ISSUE THREAD

**Issue by schmurtzm** [jtothebell/fake-08#194]
Hi, 
the last builds  eed6109 and 1b24f5d  are crashing (Segmentation fault (core dumped)) when you restore a save state automatically when the game is launched. It wasn't crashing previously in erlier builds 🤔

Do you think possible by the way to insert the commit number in the core info section ?

Thank you.

**Comment by shauninman** [comment]
At least for me/MinUI the issue first appeared in c80f6b3cdaaf2f98a37c2a72d24501ada921ff54, 6279216964e351409201e987653e3d708fd4ad78 is able to load states though I did have to add: `_vm->UpdateAndDraw();` right before the `return true;` in `retro_load_game()` for it to be able to resume a state immediately (versus manually loading a save after loading).

**Comment by jtothebell** [comment]
Thank you @schmurtzm @shauninman I should have a fix for this this week. Audio accuracy was greatly improved by a couple PR's between the last two releases, and in the process the audio state was changed, and it turns out when you try to deserialize the old audio state into the new structure it does bad things 🤦 I didn't think of this when merging those PR's and haven't payed much attention to save states after the initial implementation. I think I'm going to have to version the save state format and ignore the audio state if the state is old, but it should at least fix the crashing.
