### ISSUE TITLE
Pico-8 Cart Errors- Preprocessor not matching pico 8

### ISSUE THREAD

**Issue by Realsans22123** [jtothebell/fake-08#22]
So I keep getting errors for carts that genuinely work with pico-8, so I'm going to list the errors off from the log, and also add the carts.

Carts:
https://drive.google.com/drive/folders/1TQU9NKIOhswd8n70f1HKT-70EbrC0jIZ?usp=sharing

1. SkiFree
Setting cart audio rom data from strings
ERROR loading cart
Error: [string "s="--"d=1x=64o={}j=add...']:10; unexpected symbol near '?'

2. Mini Golf
Setting cart audio rom data from strings
ERROR loading cart
Error: [string "q=circfill r=rnd b=btn f=0p=pal..."]:2: <name> expected nar '<\146>'

3. Automata
Setting cart audio rom data from strings
ERROR loading card
Error: [string "-- 1-d cellular automata demo..."]:20: unexpected symbol near '<\151>'

And those are the 3 files I have troubles with.

**Comment by jtothebell** [comment]
Thanks for the report. I'm still working on improving compatibility, and I will take a look at these carts sometime in the next few days and see what the problem is. It's possible I already have a fix that hasn't been published yet, but it's also possible that a fix is a little ways off.

**Comment by Realsans22123** [comment]
ok

**Comment by jtothebell** [comment]
I've been looking this morning. Automata works with the code on the `MemoryCompat-Rebased` branch. On `master` right now there is no implementation for `memcpy` because the memory layout doesn't match pico 8, but that is updated in that branch. The other two carts look like tweet carts maybe? Essentially they'll need some preprocessor work because they ~~abuse~~ use some oddities of pico 8's lua flavor to save some characters. For example: `x=0y=1' is valid to assign two variables in pico 8, but not in vanilla lua (which would need `x=0 y=1` to be valid). They also use `flip()` instead of the standard update/draw loop which I'll need to implement. I added an issue for `flip()` (#23) and will use this issue to track the preprocessor problems

**Comment by Realsans22123** [comment]
Automata now works, but SkiFree and Mini Golf still doesn't work.

**Comment by Realsans22123** [comment]
i also found an ARM11 data abort in cast.p8

**Comment by Realsans22123** [comment]
https://drive.google.com/drive/folders/1P6Sq_9tjFYv2zg6k2c5RTEyZpCIHZvs2?usp=sharing

**Comment by Realsans22123** [comment]
here is the error for cast.p8:
`Setting cart audio rom data from strings
PANIC: unprotected error in call to Lua API ([string"-- raycasting demo..."]:251: attempt to call a nil value (global 'stat'))`

Now it crashes

**Comment by jtothebell** [comment]
I made a change that allows `cast.p8`to run now (the `stat` function wasn't wired up. it still isn't fully implemented, but it shouldn't crash anymore; haven't pushed a release build yet) but the movement is mostly broken, and I'll need to do more investigation to figure out why.

**Comment by Realsans22123** [comment]
ok

**Comment by jtothebell** [comment]
As far as I can tell, all the problems listed in this ticket should be resolved as of v0.0.2

**Comment by jtothebell** [comment]
Ski Free and Golf still subject to intermittent problem described in #23

**Comment by Realsans22123** [comment]
i tested both and have yet to crash so i think you did a good job at fixing it!
