### ISSUE TITLE
Try and make a port for the ds its stupid ik

### ISSUE THREAD

**Issue by Rnzei** [jtothebell/fake-08#220]

**Comment by DPS2004** [comment]
A DS port probably would not be usable, given how poorly a lot of carts run on the base (non-new) 3DS models.

**Comment by Rnzei** [comment]
Yeah ik but
Here an alr build that i think the ds can handle if it coded well or refined
https://www.reddit.com/r/flashcarts/comments/wyp9ft/comment/im3fc7a/?utm_source=share&utm_medium=web2x&context=3

**Comment by Rnzei** [comment]
Is any way you guys can refined it?

**Comment by jtothebell** [comment]
No current plans to work on this. I don't have a DS, and I don't think it's a good candidate because I doubt I can optimize Fake-08 better than Pico-8, and the DS's processor is well below Pico-8 minimum spec. Anyone out there who wants to try, it sounds like just disabling audio would be the best way to save cycles and have some games playable.
