### ISSUE TITLE
Some carts not working with "eRROR LOADING CART LUA"

### ISSUE THREAD

**Issue by Archonic944** [jtothebell/fake-08#25]
Some pico-8 carts, when loaded, do not boot and instead display on the console "eRROR LOADING CART LUA"
The games I have had trouble with are:

 - Dodge
 - Alone in pico
 - Warehouse Panic
I am using .p8.png files on my 3DS using the .3dsx executable.

**Comment by jtothebell** [comment]
Thanks for the report. I think the first two are probably related to adding menu items. Not sure about the third one, but I will take a closer look at all three when I can. Currently working on integrating a lua variant that should be fully compatible with Pico 8 (z8lua) which should also improve compatibility and may help with this.

**Comment by Archonic944** [comment]
Thanks for replying so fast, can't wait to be able to play all my favorite pico-8 games, and thank you for making this great player!

**Comment by jtothebell** [comment]
I just looked at each of those carts and found a few issues

- Dodge and Warehouse panic use the `?` shorthand for printing. This should be fixed with the lua update I referenced above. I can't commit to a timeline, but that is my top priority for Fake-08 right now. If you feel up to it, you can edit the carts to replace the shorthand `?` with the longhand function call `print` (ie `?_txt,_x,_y+1,1` changes to `print(_txt,_x,_y+1,1)`). This alone looks like it makes warehouse panic work
- Dodge and Alone in Pico use the `menuitem` function. I don't  have support for the menu yet, but I just pushed an update that at least should allow it to run (just an empty function to call so it doesn't panic). This along with the print change makes Dodge playable.
- Alone in Pico also has what looks like a problem with the current lua preprocessor I'm using, but after I manually changed the lua to what I think it should be, it crashes the whole 3ds... so I'll have to do some more investigating, but I'm going to wait to do that until after the lua update.
- Warehouse panic looks like it might have some minor visual issues (black pixels around sprites that should be transparent). Another thing I'll circle back to when I can.

**Comment by Archonic944** [comment]
I have more titles to add to the list:

- Desert Land
- Pool (I'm not sure which one it is)
- Slacker
- Polar Panic

**Comment by jtothebell** [comment]
With the release of v0.0.2, I believe all the carts listed in this ticket run. There are a couple that still have issues, but I'm going to break those out into their own tickets and then close this one.

**Comment by Airwalk16** [comment]
I am getting this error message on Domain Conflict, Mr. Jon Bell!!!
